

CREATE TABLE PLANETA (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    NOMBRE VARCHAR(20) NOT NULL,
    DISTANCIA_SOL VARCHAR(15),
    GRABEDAD DECIMAL(7,2),
    ROCOSO BOOLEAN,
    NUM_SATELITES SMALLINT,
    ORBITA VARCHAR(50),
    CONSTRAINT ID_SATELITES_PK PRIMARY KEY (ID)
);


CREATE TABLE SATELITE (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY, -- Id autonumérico
    NOMBRE VARCHAR(20) NOT NULL,
    PLANETA INTEGER,
    DESCUBIERTO_POR VARCHAR(40),
    DISTANCIA_AL_PLANETA VARCHAR(15),
    AÑO_DESCUBRIMIENTO DATE,
    TEMPERATURA_MEDIA SMALLINT,
    GRABEDAD DECIMAL(7,2),
    MISIONES_ESPACIALES BOOLEAN,
    TAMAÑO_PLANETA CHAR(1),
    FOTO VARCHAR(30),
    CONSTRAINT ID_SATELITE_PK PRIMARY KEY (ID),
    CONSTRAINT PLAN_SATELITE_FK FOREIGN KEY (PLANETA) REFERENCES PLANETA (ID)
);